### ISSUE TITLE
As a lightcurve user, I want to hardcode a target color index

### ISSUE THREAD

**Issue by typpo** [typpo/astrokit#105]
If specified, image reductions will use this color index

"  If the images are in one filter, than use an assumed value for the color
      index of the target. For asteroids, that would be B-V = 0.8 or V-R = 0.45.
      These are slightly redder than true solar color but, then again, most
      asteroids are redder than true solar color."

**Comment by judymou** [comment]
416888bca0b6344fc6d11f00f4748
