### ISSUE TITLE
As a user, I want the software to load the image timestamp automatically from FITS data

### ISSUE THREAD

**Issue by typpo** [typpo/astrokit#38]
FITS data will almost always have a timestamp.  Load it automatically into `ImageAnalysis.image_datetime`

Consider doing the same for latlng, elevation, and other metadata if available!

**Comment by judymou** [comment]
image_datetime is already auto read, and there are no fields for other info (e.g. latlng).

https://heasarc.gsfc.nasa.gov/docs/fcg/standard_dict.html
