### ISSUE TITLE
Upload page is broken visually

### ISSUE THREAD

**Issue by typpo** [typpo/astrokit#49]
When you upload a large number of files, it looks broken

Also, we should disable the image preview, because FITS files cannot be viewed in browser.

![image](https://user-images.githubusercontent.com/310310/35957305-cd5b2ab2-0c4f-11e8-8233-813da3e1a77e.png)

**Comment by judymou** [comment]
https://github.com/typpo/astrokit/commit/00d498ca8c75b251ac85a6970f470416c1374d49
