### ISSUE TITLE
As a reduction user, I want to be able to manually enter my target's color index

### ISSUE THREAD

**Issue by typpo** [typpo/astrokit#52]
Some target CIs don't change from night to night, so it is acceptable to just enter a hard value (Warner 119).  This color index could be inputted on the reductions page or the main lightcurve page (to apply to all images)

**Comment by typpo** [comment]
I added a placeholder in the reduction.html template: 7d563fc

**Comment by judymou** [comment]
1. make sure deletion of the manual color index work
2. Use the manual color index instead of the paired image.

**Comment by typpo** [comment]
Done
